# Clase 2: primeros pasos en python
Profesor: Emiliano López - `emiliano.lopez@gmail.com` 


- Instalación conda ✅
- Notebooks: jupyter lab ✅ 
- Obtener ayuda en el intérprete: ``help()``, ``dir()``
- Tipos de datos: ``int, str, float``
- Contenedor: lista (``list``)
- Parseo de datos `str`: método ``split``
- Ciclo repetitivo: ``for``
- Bibliografía: Tutorial de Python oficial, pag. 8 a 14..
- Keywords: **contenedores**, **tipos de datos**

## Jupyter notebook

Tiene características particulares que lo hacen atractivo para el análisis exploratorio de datos. La similitud respecto al intérprete interactivo se corresponde que no necesitamos poner ``print()`` para que nos muestre el contenido de alguna variable o contenedor. 

Tenemos dos tipos de celdas: 

- Markdown: texto con caracteres especiales que le dan formato
- Código: ingresamos código python (soporta otros lenguajes también)

Parados con el cursor en la celda se ejecuta al presionar ``shift-enter``.

Markdown soporta código Latex (para escribir ecuaciones matemáticas). Lo escribimos entre doble signo pesos:

$$\int_0^\inf 2*\pi$$

Ahora voy a mostrar como elevar un número x al cuadrado: $x^2$

$v_i = \sum t*4$

In [ ]:
# mostrar un simple mensaje
print("Hola")

## Variables y tipos

La unidad básica para almacenar información son las variables, para ello usamos una asignación con el signo igual, donde a su izquierda escribimos el identificador y a su derecha el valor que pretendemos asignarle. 
Veamos tres variables con identificador ``a, b, c``.

In [ ]:
a = "holA"
b = 3
c = 1.2

print(a, b, c)

print(a)
print(b)
print(c)

In [ ]:
resultado = b + c

print(resultado)

In [ ]:
resultado2 = a*b
print(resultado2)

Cada variable tiene un tipo de dato asociado, este tipo de dato tiene que ver con las operaciones que podremos realizar. Veamos como obtener el tipo de dato de cada variable:

In [ ]:
type(a)

In [ ]:
type(b)

In [ ]:
type(c)

In [ ]:
a = "blablalbaasdasdfsdgsdfg"

In [ ]:
len(a)

También podemos hacer asignaciones múltiples en una sola línea, acá por ejemplo asignamos:
- el número ``10`` a la variable ``a``
- la cadena ``black bird`` a la variable ``b``
- el número ``3.1415`` a la variable ``c``

In [ ]:
a,b,c = 10, "black bird", 3.1415

In [ ]:
type(b)

**¿De qué tipo es el contenedor si almacenamos las 3 variables de la derecha bajo un único identificador en vez de tres?**

In [ ]:
unico_contenedor = (10, "black bird", 3.1415)

In [ ]:
type(unico_contenedor)

In [ ]:
unico_contenedor[2]

In [ ]:
len(unico_contenedor)

Otro tipo de contenedor es la **lista**, podemos crear manualmente una lista combinando diferente tipos de datos:

In [ ]:
lista_variada = ["dolina", 38, "fontanarosa", 39, "azurduy", 3.1415,  "fermat", 22]

Vemos qué tipo de dato es el almacenado en la posición dos de la lista ``curso``

In [ ]:
type(lista_variada)

In [ ]:
lista_variada[3]

In [ ]:
len(lista_variada)

In [ ]:
lista_variada[5] = 222

In [ ]:
lista_variada

In [ ]:
lista_variada.append(6.6)

In [ ]:
lista_variada

In [ ]:
lista_variada.append(b)

In [ ]:
lista_variada

In [ ]:
lista_variada.append(unico_contenedor)

In [ ]:
lista_variada

In [ ]:
lista_variada[len(lista_variada)-1][0]

In [ ]:
lista_variada[-1]

In [ ]:
lista_variada

## Archivos de texto en python

Vamos a cargar en nuestro programa el contenido de un archivo, esta acción es denominada lectura. Para eso son necesarias dos acciones:
- apertura
- lectura
- cierre

Para abrirlo usamos la función ``open`` y entre comillas debemos poner la ruta al archivo al que pretendemos acceder.
**OJO: dependiendo de tu sistema operativo es el formato de la ruta que debemos poner (YA NO MAS SI USAMOS PATHLIIB)**

In [ ]:
# IMPORTAMOS de la lib estándar
from pathlib import Path

# esto depende de la ruta de cada archivo
ruta_actual = Path.cwd() # devuelve path del presente notebook
path_archi_cumples = ruta_actual.parent / "datos" / "queloscumplas.txt"

# 1) abrimos el archivo
archi_cumples = open(path_archi_cumples, 'r', encoding='utf-8')

# 2) leemos TODO su contenido y lo almacenamos en un contenedor
contenido_cumples = archi_cumples.readlines()

# 3) cerramos el archivo, ya tenemos su contenido
archi_cumples.close()

En contenido tenemos un contenedor, accedemos a cada elemento poniendo entre corchetes una posición (índice numérico). El primero corresponde a la posición 0, por lo tanto si son N renglones, tendremos entre 0 y N-1.

In [ ]:
type(contenido_cumples)

In [ ]:
# accedemos al elemento
contenido_cumples[0]

In [ ]:
# con índice negativo accedemos al último
contenido_cumples[-1]

In [ ]:
# vemos la cantidad de elementos de la lista
# en este caso equivale a la cantidad de renglones del archivo
n = len(contenido_cumples)

# con esto obtengo el elemento de la mitad, 
# la // es el operador de divisón entera
mitad = n // 2 - 1
contenido_cumples[mitad]

In [ ]:
# otra forma de acceder al último elemento
contenido_cumples[n-1]

## Slices (porciones/rebanadas)

Podemos extraer una porción de la lista si le decimos entre qué índices: índice inicial y último. ¿Incluye el último?

In [ ]:
contenido_cumples[10:15]

In [ ]:
contenido_cumples[15:20]

In [ ]:
contenido_cumples[10:20]

In [ ]:
type(contenido_cumples[-10:])

In [ ]:
# Así veríamos la primera fecha
la_primera = contenido_cumples[0]

In [ ]:
type(la_primera)

In [ ]:
fecha_separada = la_primera.split(sep="-")

In [ ]:
fecha_separada

In [ ]:
anio = fecha_separada[0]
mes = fecha_separada[1]

In [ ]:
dia_y_hora = fecha_separada[2].split(sep=" ")

In [ ]:
dia = dia_y_hora[0]

In [ ]:
hora = dia_y_hora[1]

In [ ]:
# minuto
minuto = int(contenido_cumples[4].split(":")[1])
minuto

In [ ]:
# con un slice nos quedamos con dia y la hora
print(contenido_cumples[10])
contenido_cumples[10][8:13]

## Ciclos repetitivos/iterativos

Como la vida es corta necesitamos ciclos repetitivos. Veamos uno a uno todos los elementos de la lista que creamos previamente:

In [ ]:
meses = "enero febrero"
for letra in meses:
    print(letra)

In [ ]:
for fecha_hora in contenido_cumples[0:10]:
    print(fecha_hora, end="")

In [ ]:
for elemento in lista_variada:
    print(elemento)
print("esto")

El ciclo previo se denomina ``for`` y va asignando uno a uno los elementos de la lista curso a la variable ``elemento``. 
La particularidad de **Python** es que cada acción que deba ejecutarse dentro del ciclo for se indica con **cuatro espacios**. En el siguiente ejemplo, vemos que una vez que termina el ciclo muestra se ejecuta la línea ``print("Arlt")``.

In [ ]:
for elemento in lista_variada:
    print(elemento)
print("Arlt")

**Observemos atentamente** el cambio que se produce si dejamos 4 espacios en el ``print`` y por ende pasa a estar dentro del ciclo repetitivo:

In [ ]:
for elemento in lista_variada:
    print(elemento)
    print("Arlt")

## Parseando datos

Vamos a excluir y/o seleccionar datos del archivo usando el método ``split()`` que se aplica a cadenas (``str``):

In [ ]:
for renglon in contenido_cumples[0:10]:
    fecha, hora = renglon.split()
    h,m,s = hora.split(":")
    print(fecha, s)

In [ ]:
for una_fecha in contenido_cumples[:10]:
    anio, mes, todo = una_fecha.split("-")
    print(mes)

In [ ]:
en_diciembre = 0
for una_fecha in contenido_cumples:
    anio, mes, todo = una_fecha.split("-")
    if mes == "12":
        en_diciembre = en_diciembre + 1
print(en_diciembre)

# Actividades con datos reales

## Dataset 1: Localidades de Argentina
Preguntas para resolver con bucles y condicionales:

### Ej1: ¿Cuántas localidades hay en la provincia de santa fe?

- Estructura del condicional if

```python
if CONDICION:
    ACCIONES QUE SE EJECUTAN
    CUANDO ES VERDADERA 
    LA CONDICION
else:
    ACCIONES QUE SE 
    EJECUTAN CUANDO
    LA CONDICION FUE FALSA
```

- Sección del condicional y contador 

```python
cont_sfe = 0
if provincia == "Santa Fe":
    cont_sfe = cont_sfe + 1 # cont_sfe += 1
```

- Sección del for + contador
```python
for una_loca in localidades:
    provincia = una_loca.split.........
    BLOQUE DEL CONTADOR
```

In [2]:
from pathlib import Path

# esto depende de la ruta de cada archivo
ruta_actual = Path.cwd() # devuelve path del presente notebook

In [3]:
path_localidades = ruta_actual.parent / "datos" / "localidades.csv"

# Usando with (context managers) nos olvidamos de cerrar el archivo
with open(path_localidades, 'r', encoding='utf-8') as f:
    localidades = f.readlines()

# Celda vacía para que los estudiantes cuenten localidades por provincia

In [13]:
localidades[1].split(",")[-1].strip() == '"Córdoba"'

True

In [21]:
prov_int = '"Córdoba"'
cont = 0
for una_loca in localidades[1:]:
    provincia = una_loca.split(",")[-1].strip()
    if provincia == prov_int:
        cont = cont + 1

In [22]:
cont

514

## Ej2: ¿Cuál es la provincia con más localidades?
- ¿Cuál es el departamento con menos localidades?

In [24]:
contadores = {}

In [25]:
type(contadores)

dict

In [26]:
contadores["sfe"] = 1

In [28]:
contadores["cba"] = 7

In [29]:
contadores

{'sfe': 1, 'cba': 7}

In [30]:
contadores['sfe'] = contadores['sfe'] + 1

In [38]:
contadores

{'sfe': 2, 'cba': 7, 0: 55}

In [39]:
contadores['sfe'] = 0

In [40]:
contadores

{'sfe': 0, 'cba': 7, 0: 55}

- Estrategia general

    - paso 1: crear el diccionario de provincias inicializadas en 0
    - paso 2: contar las localidades de cada provincia
    - paso 3: identificar la provincia con mas localidades

**Paso 1**
```python
for una_loca in localidades[1:]:
    provincia = una_loca.split(",")[-1].strip()
    contador_prov[provincia] = 0
```

**Paso 2**
```python
for una_loca in localidades[1:]:
    provincia = una_loca.split(",")[-1].strip()
    contador_prov[provincia] += 1 
```

In [46]:
# paso 1
contador_prov = dict()
for una_loca in localidades[1:]:
    provincia = una_loca.split(",")[-1].strip()
    contador_prov[provincia] = 0

# paso 2
for una_loca in localidades[1:]:
    provincia = una_loca.split(",")[-1].strip()
    contador_prov[provincia] += 1

In [48]:
contador_prov

{'"Córdoba"': 514,
 '"Mendoza"': 209,
 '"Buenos Aires"': 895,
 '"Catamarca"': 170,
 '"La Rioja"': 95,
 '"Chubut"': 91,
 '"Entre Ríos"': 182,
 '"Formosa"': 63,
 '"Jujuy"': 160,
 '"Misiones"': 140,
 '"Neuquén"': 59,
 '"Río Negro"': 149,
 '"Tucumán"': 109,
 '"Salta"': 131,
 '"San Luis"': 91,
 '"San Juan"': 95,
 '"Santa Fe"': 389,
 '"Corrientes"': 76,
 '"Chaco"': 91,
 '"La Pampa"': 89,
 '"Santa Cruz"': 26,
 '"Santiago del Estero"': 160,
 'Antártida e Islas del Atlántico Sur"': 4,
 '"Ciudad Autónoma de Buenos Aires"': 49}

In [52]:
cant_mayor = 0
prov_mayor = ""
for prov,cantidad in contador_prov.items():
    if cantidad > cant_mayor:
        cant_mayor = cantidad
        prov_mayor = prov
        
print(prov_mayor,cant_mayor)

"Buenos Aires" 895

In [59]:
max_key = max(contador_prov, key=contador_prov.get)
print(max_key, contador_prov[max_key])  # 'b'

"Buenos Aires" 895

In [62]:
# Listas
temperaturas = [12.5, 13.0, 22, 28]
fechas = ['2025-09-06','2025-09-07', '2025-09-08', '2025-09-09']

In [66]:
panama = {
    'temperatura': temperaturas,
    'fecha': fechas 
}

In [71]:
panama

{'temperatura': [12.5, 13.0, 22, 28],
 'fecha': ['2025-09-06', '2025-09-07', '2025-09-08', '2025-09-09']}

In [72]:
import pandas as pd

In [74]:
df = pd.DataFrame(panama)

In [78]:
df

   temperatura       fecha
0         12.5  2025-09-06
1         13.0  2025-09-07
2         22.0  2025-09-08
3         28.0  2025-09-09

In [81]:
df['temperatura']

0    12.5
1    13.0
2    22.0
3    28.0
Name: temperatura, dtype: float64

In [82]:
import polars as pl

In [83]:
df_pl = pl.DataFrame(panama)

In [84]:
df_pl

shape: (4, 2)
┌─────────────┬────────────┐
│ temperatura ┆ fecha      │
│ ---         ┆ ---        │
│ f64         ┆ str        │
╞═════════════╪════════════╡
│ 12.5        ┆ 2025-09-06 │
│ 13.0        ┆ 2025-09-07 │
│ 22.0        ┆ 2025-09-08 │
│ 28.0        ┆ 2025-09-09 │
└─────────────┴────────────┘

## Dataset 2: Nombres de personas nacidas en Argentina (1922-2015)
Preguntas para resolver:
- ¿En qué año nacieron más personas?
- ¿En qué año hubo menor 'variación' de nombres?
- ¿En qué año hubo mayor 'variación' de nombres?
- ¿Cuántas personas nacieron en 1981?
- Graficar el número de nacimientos por año
- ¿Cómo calcular la cantidad de nombres más frecuentes en cada década?

In [ ]:
# path al archivo
path_nombres = ruta_actual.parent / "datos" / "historico-nombres.csv"
with open(path_nombres, 'r', encoding='utf-8') as f:
    nombres = f.readlines()

# Celda vacía: ¿Cuántas personas nacieron en 1981?

In [ ]:
nombres[:5]

In [ ]:
import pandas as pd
import polars as pl

In [ ]:
pl.read_csv(path_nombres)